//------------------------------------------------------------------------------
// <auto-generated>
//    Este c贸digo se gener贸 a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicaci贸n.
//    Los cambios manuales en este archivo se sobrescribir谩n si se regenera el c贸digo.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBoxSale.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class EMPRESA
    {
        public EMPRESA()
        {
            this.USUARIO = new HashSet<USUARIO>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage="Nombre del comercio es requerido")]
        public string Nombre { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        [MaxLength(ErrorMessage="Solo se permiten 300 caracteres.")]
        public string Direccion { get; set; }
        [MaxLength(ErrorMessage="Solo se permiten 12 d韌itos.")]
        public string Telefono { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual ICollection<USUARIO> USUARIO { get; set; }
    }
}
