//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBoxSale.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    
    public partial class PRODUCTO
    {
        public PRODUCTO()
        {
            this.DETALLEVENTA = new HashSet<DETALLEVENTA>();
            this.PROMOCION = new HashSet<PROMOCION>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage="Nombre requerido")]
        public string Nombre { get; set; }
        [Required(ErrorMessage = "Precio de venta requerido")]
        [Display(Name = "Precio de Venta")]
        public Nullable<double> PrecioMostrador { get; set; }
        [Required(ErrorMessage = "Precio de compra requerido")]
        [Display(Name = "Precio de compra requerido")]
        public Nullable<double> PrecioCompra { get; set; }
        public Nullable<double> Existencia { get; set; }
        [Display(Name="Stock Minimo")]
        public Nullable<double> StockMin { get; set; }
        public string Imagen { get; set; }
        public Nullable<bool> Activo { get; set; }
        [Display(Name = "Unidad de Medida")]
        public Nullable<int> UnidadId { get; set; }
        [Display(Name = "Proveedor")]
        public Nullable<int> ProveedorId { get; set; }
        [Display(Name = "Categoría")]
        public Nullable<int> CategoriaId { get; set; }
        public string SKU { get; set; }
        public HttpPostedFileBase FileImg { get; set; }
    
        public virtual CATEGORIA CATEGORIA { get; set; }
        public virtual ICollection<DETALLEVENTA> DETALLEVENTA { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        public virtual UNIDADMEDIDA UNIDADMEDIDA { get; set; }
        public virtual ICollection<PROMOCION> PROMOCION { get; set; }
    }
}
