//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBoxSale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public PRODUCTO()
        {
            this.DETALLEVENTA = new HashSet<DETALLEVENTA>();
            this.PROMOCION = new HashSet<PROMOCION>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<double> PrecioMostrador { get; set; }
        public Nullable<double> PrecioCompra { get; set; }
        public Nullable<double> Existencia { get; set; }
        public Nullable<double> StockMin { get; set; }
        public string Imagen { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> UnidadId { get; set; }
        public Nullable<int> ProveedorId { get; set; }
        public Nullable<int> CategoriaId { get; set; }
    
        public virtual CATEGORIA CATEGORIA { get; set; }
        public virtual ICollection<DETALLEVENTA> DETALLEVENTA { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        public virtual UNIDADMEDIDA UNIDADMEDIDA { get; set; }
        public virtual ICollection<PROMOCION> PROMOCION { get; set; }
    }
}
