//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBoxSale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPOPROMOCION
    {
        public TIPOPROMOCION()
        {
            this.PROMOCION = new HashSet<PROMOCION>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual ICollection<PROMOCION> PROMOCION { get; set; }
    }
}
