//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBoxSale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.USUARIOROLES = new HashSet<USUARIOROLES>();
            this.VENTA = new HashSet<VENTA>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string NombreUsuario { get; set; }
        public string Password { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<int> EmpresaId { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual ICollection<USUARIOROLES> USUARIOROLES { get; set; }
        public virtual ICollection<VENTA> VENTA { get; set; }
    }
}
