//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBoxSale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.USUARIOROLES = new HashSet<USUARIOROLES>();
            this.VENTA = new HashSet<VENTA>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string NombreUsuario { get; set; }
        public string Password { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<int> EmpresaId { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual ICollection<USUARIOROLES> USUARIOROLES { get; set; }
        public virtual ICollection<VENTA> VENTA { get; set; }
    }
}
